### ISSUE TITLE
Newest Community Store update seemed to add all orders from all users.

### ISSUE THREAD

**Issue by mdius** [JeRoNZ/community_store_order_history#6]
I did an update earlier this week and now the order history shows all the orders from all the users. It used to only show for only the user logged in.

**Comment by katalysis** [comment]
We're also seeing this issue

**Comment by mdius** [comment]
I installed past versions of Community Store. It fixed itself when I put v2.6.2 back in. So something changed from version 2.6.2 to 2.6.3.
There was a change in the /community_store\src\CommunityStore\Order\OrderList.php
If I copy and paste the data from the 2.6.2 version to my current version the issue goes away.
But I am not smart enough to know how to fix it.

**Comment by mdius** [comment]
I think I maybe hacked a fix?
Made an Order folder CommunityStoreOrderHistory\Src\ here and added the 2.6.2 version of community_store\src\CommunityStore\Order\OrderList.php and put it in that folder.
Opened it and changed the namespace to:
namespace Concrete\Package\CommunityStoreOrderHistory\Src\Order;

Then opened CommunityStoreOrderHistory\Src\OrderList.php and changed the line:
use Concrete\Package\CommunityStore\Src\CommunityStore\Order\OrderList as OL;
to
use Concrete\Package\CommunityStoreOrderHistory\Src\Order\OrderList as OL;
It seems to work until there is a real fix for it.
Please understand I am not a programmer and I don't know if this could cause any issues. I am personally not seeing anything on my end though.
So do this at your own risk.

**Comment by JeRoNZ** [comment]
This issue here is that the orderlist the package uses is an extension of the community store's orderlist. That had a PR #833 back in January that added a number of previously undeclared variables (necessary for PHP8.x) but unfortunately, they were declared as private, which means that they become inaccessible to any class that extends it. Thus when building the query, the extended class cannot set the parent's value and assumes all orders are to be included.

I'm going to raise this as an issue with community store, but I'll also release a workaround which is to add the cID and its associated method to the override. Because the finalizeQuery method is also overridden, the local copy will now be used.

packages/community_store_order_history/src/OrderList.php:

```
protected $cID = null;
public function setCustomerID($cID)
{
	$this->cID = is_numeric($cID) ? (int) $cID : null;
}
```
